import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='bg-stone-100 p-8'>
          <nav className='container'>
            <ul className='flex gap-4'>
              <li>
                <Link
                  href='/'
                  className='text-sm font-medium uppercase text-stone-400'
                >
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href='/posts'
                  className='text-sm font-medium uppercase text-stone-400'
                >
                  Posts
                </Link>
              </li>
            </ul>
          </nav>
        </header>

        <main className='container p-8'>{children}</main>

        <footer className='bg-stone-100 text-sm font-medium uppercase text-stone-400 py-4 px-8'>
          <div className='container'>
            <p>Footer</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
